### ISSUE TITLE
Fix `pypi.yaml`

### ISSUE THREAD

**Issue by adosar** [adosar/aidsorb#8]
```yaml
publish-to-pypi:
  name: Publish Python 🐍 distribution 📦 to PyPI
  if: startsWith(github.ref, 'refs/tags/[0-9]+.[0-9]+.[0-9]+.')  # only publish to PyPI on SemVer tags
```

Since PyPI checks for compatible version scheme **the regex is not needed**.
